const booksListData = [
  {
    id: "1",
    title: "1984",
    author: "George Orwell",
    genre: "Dystopian",
    publishedYear: 1949,
    coverImage: "",
    // "https://example.com/1984-cover.jpg",
    isRead: true,
    isFavorite: true,
    createdAt: "2023-01-15T10:00:00Z",
    status: "finished",
    description:
      "A dystopian novel set in a totalitarian society where the Party controls everything, including thought. A timeless critique of surveillance and government control.",
    tags: ["classic", "political", "dystopia"],
  },
  {
    id: "2",
    title: "The Hobbit",
    author: "J.R.R. Tolkien",
    genre: "Fantasy",
    publishedYear: 1937,
    coverImage: "",

    // coverImage: "https://example.com/the-hobbit-cover.jpg",
    isRead: false,
    isFavorite: false,
    createdAt: "2023-03-02T15:30:00Z",
    status: "to read",
    description:
      "The story of Bilbo Baggins, a hobbit who embarks on an unexpected adventure that takes him through Middle-earth.",
    tags: ["fantasy", "adventure", "classic"],
  },
  {
    id: "3",
    title: "Becoming",
    author: "Michelle Obama",
    genre: "Biography",
    publishedYear: 2018,
    coverImage: "",

    // coverImage: "https://example.com/becoming-cover.jpg",
    isRead: true,
    isFavorite: true,
    createdAt: "2023-05-20T14:00:00Z",
    status: "finished",
    description:
      "Michelle Obama's memoir about her life, focusing on her roots, her time in the White House, and the experiences that shaped her as a person.",
    tags: ["inspirational", "political", "memoir"],
  },
  {
    id: "4",
    title: "The Silent Patient",
    author: "Alex Michaelides",
    genre: "Mystery",
    publishedYear: 2019,
    coverImage: "",

    // coverImage: "https://example.com/the-silent-patient-cover.jpg",
    isRead: false,
    isFavorite: false,
    createdAt: "2023-06-10T12:15:00Z",
    status: "reading",
    description:
      "A psychological thriller about a woman who shoots her husband and then refuses to speak. A psychotherapist becomes obsessed with uncovering the truth behind her silence.",
    tags: ["thriller", "psychological", "mystery"],
    readingProgress: {
      currentPage: 120,
      totalPages: 350,
      updatedAt: "2023-06-20T10:00:00Z",
    },
  },
  {
    id: "5",
    title: "The Power of Habit",
    author: "Charles Duhigg",
    genre: "Self-Help",
    publishedYear: 2012,
    coverImage: "",

    // coverImage: "https://example.com/the-power-of-habit-cover.jpg",
    isRead: true,
    isFavorite: false,
    createdAt: "2023-02-10T08:45:00Z",
    status: "finished",
    description:
      "An exploration of how habits are formed and how they can be changed, offering insight into personal and professional growth.",
    tags: ["self-help", "psychology", "growth"],
  },
  {
    id: "6",
    title: "Sapiens: A Brief History of Humankind",
    author: "Yuval Noah Harari",
    genre: "History",
    publishedYear: 2011,
    coverImage: "",

    // coverImage: "https://example.com/sapiens-cover.jpg",
    isRead: false,
    isFavorite: true,
    createdAt: "2023-04-12T17:00:00Z",
    status: "to read",
    description:
      "A fascinating exploration of the history of humankind, from the dawn of Homo sapiens to the present day.",
    tags: ["history", "non-fiction", "philosophy"],
  },
  {
    id: "7",
    title: "The Catcher in the Rye",
    author: "J.D. Salinger",
    genre: "Fiction",
    publishedYear: 1951,
    coverImage: "",

    // coverImage: "https://example.com/catcher-in-the-rye-cover.jpg",
    isRead: true,
    isFavorite: false,
    createdAt: "2023-03-25T09:00:00Z",
    status: "finished",
    description:
      "The story of Holden Caulfield, a disillusioned teenager who grapples with depression, alienation, and the transition from childhood to adulthood.",
    tags: ["classic", "coming-of-age", "fiction"],
  },
  {
    id: "8",
    title: "Dune",
    author: "Frank Herbert",
    genre: "Sci-Fi",
    publishedYear: 1965,
    coverImage: "",

    // coverImage: "https://example.com/dune-cover.jpg",
    isRead: false,
    isFavorite: true,
    createdAt: "2023-06-01T11:30:00Z",
    status: "to read",
    description:
      "A science fiction epic set in a distant future where noble houses vie for control over the desert planet Arrakis, the only source of the valuable spice melange.",
    tags: ["sci-fi", "epic", "space"],
  },
  {
    id: "9",
    title: "Dune",
    author: "Frank Herbert",
    genre: "Sci-Fi",
    publishedYear: 1965,
    coverImage: "",

    // coverImage: "https://example.com/dune-cover.jpg",
    isRead: false,
    isFavorite: true,
    createdAt: "2023-06-01T11:30:00Z",
    status: "to read",
    description:
      "A science fiction epic set in a distant future where noble houses vie for control over the desert planet Arrakis, the only source of the valuable spice melange.",
    tags: ["sci-fi", "epic", "space"],
  },
];

export default booksListData;
